version: 2

models:
  - name: stg_customers
    description: "Stage table for customers data"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        data_tests:
          - not_null
          - unique
      - name: customer_unique_id
        description: "Unique ID for each customer, used to identify repeat customers"
        data_tests:
          - not_null
      - name: customer_zip_code_prefix
        description: "Zip code prefix of the customer's address"
      - name: customer_city
        description: "City where the customer resides"
      - name: customer_state
        description: "State where the customer resides"

  - name: stg_products
    description: "stage table for products data"
    columns:
      - name: product_id
        description: "unique identifier for each product"
        data_tests:
          - not_null
          - unique
      - name: product_category_name
        description: "category of the product"
      - name: product_name_length
        descriprtion: "length of product name"
      - name: production_description_length
        description: "length of product description"
      - name: product_photos_qty
        description: "number of photos for the product"
      - name: product_weight_g
        description: "weight of the product in grams"
      - name: product_length_cm
        description: "length of the product in centimeters" 
      - name: product_height_cm
        description: "height of the product in centimeters"
      - name: product_width_cm
        description: "width of the product in centimeters" 
  
  - name: stg_sellers
    description: "Stage table for sellers data"
    columns:
      - name: seller_id
        description: "Unique identifier for each seller"
        data_tests:
          - not_null
          - unique
      - name: seller_zip_code_prefix
        description: "Zip code prefix of the seller's address"
      - name: seller_city
        description: "City where the seller is located"
      - name: seller_state
        description: "State where the seller is located"
  
  - name: stg_orders
    descriprtion: "Stage table for orders data"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        data_tests:
          - not_null
          - unique
      - name: customer_id
        description: "Unique identifier for the customer who placed the order"
      - name: order_status
        description: "Status of the order (e.g., delivered, shipped, canceled)"
      - name: order_purchase_timestamp
        description: "Timestamp when the order was purchased"
      - name: order_approved_at
        description: "Timestamp when the order was approved"
      - name: order_delivered_carrier_date
        description: "Date when the order was delivered to the carrier"
      - name: order_delivered_customer_date
        description: "Date when the order was delivered to the customer"
      - name: order_estimated_delivery_date
        description: "Estimated delivery date for the order"
  
  - name: stg_order_items
    descriprtion: "Stage table for order items data"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        data_tests:
          - not_null
      - name: order_item_id
        description: "Unique identifier for each item in the order"
        data_tests:
          - not_null
      - name: product_id
        description: "Unique identifier for the product"
        data_tests:
          - not_null
      - name: seller_id
        description: "Unique identifier for the seller of the product"
      - name: shipping_limit_date
        description: "Date by which the item should be shipped"
      - name: price
        description: "Price of the item"
      - name: freight_value
        description: "Freight value for the item"
  
  - name: stg_order_payments
    description: "Stage table for order payments data"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        data_tests:
          - not_null
      - name: payment_sequential
        description: "Sequential number of the payment in the order"
      - name: payment_type
        description: "Type of payment (e.g., credit card, boleto)"
      - name: payment_installments
        description: "Number of installments for the payment"
      - name: payment_value
        description: "Total value of the payment"
  
  - name: stg_order_reviews
    description: "Stage table for order reviews data"
    columns:
      - name: review_id
        description: "Unique identifier for each review"
        data_tests:
          - not_null
          - unique
      - name: order_id
        description: "Unique identifier for the order being reviewed"
      - name: review_score
        description: "Score given by the customer in the review"
      - name: review_comment_title
        description: "Title of the review comment"
      - name: review_comment_message
        description: "Message of the review comment"
      - name: review_creation_date
        description: "Date when the review was created"
      - name: review_answer_timestamp
        description: "Timestamp when the seller answered the review"
    
sources:
  - name: raw
    tables:
      - name: raw_customers
        description: "Raw customers data from Olist"
      - name: raw_products
        descriprtion: "Raw products data from Olist"
      - name: raw_sellers
        descriprtion: "Raw sellers data from Olist"
      - name: raw_orders
        description: "Raw orders data from Olist"
      - name: raw_order_items
        description: "Raw order items data from Olist"
      - name: raw_order_payments
        description: "Raw order payments data from Olist"
      - name: raw_order_reviews
        description: "Raw order reviews data from Olist"